#!/bin/bash

DIR="$HOME/.dragon_12"
source ./dragon_12_vars_config.sh

if [ ! -d $HOME/.dragon_12 ]
then
    mkdir $DIR
fi

if [ ! -f $HOME/.dragon_12/dragon_12.sh ]&&[ ! -f $HOME/.dragon_12/dragon_12_vars_config.sh ]
then
    echo 'Hard linking files to program local directory.'
    chmod 755 dragon_12.sh
    chmod 644 dragon_12_vars_config.sh
    ln dragon_12.sh $DIR
    cp dragon_12_vars_config.sh $DIR
fi

if [ "$1" == 'all' ]
then
    if [ -z "$( grep dragon_12 $HOME/.bashrc )" ]
    then
	echo 'Adding environment variables to .bashrc.'
	echo 'PATH=$PATH:$HOME/.dragon_12' >> $HOME/.bashrc
	echo 'source $HOME/.dragon_12/dragon_12_vars_config.sh' >> $HOME/.bashrc
    else
	echo 'Dragon 12 shell tool is already configured'
    fi

    if [ -f assembler.zip ]
    then
	unzip assembler.zip
	mv H* $DIR
	mv s* $DIR
    fi
fi

if [ ! -d $DRAGON_AS12_PATH/ ]
then
    mkdir $DRAGON_AS12_PATH/
fi

if [ ! -f $DRAGON_AS12_PATH/$DRAGON_AS ]
then
    cd $DRAGON_AS12_PATH/
    wget 'http://dankohn.info/projects/68HC11/AsmIDE/asmide340.zip'
    if [ -f asmide340.zip ]
    then
        unzip asmide340.zip
        rm asmide340.zip
        cd -
        if [ "$( md5sum $DRAGON_AS12_PATH/$DRAGON_AS | cut --delimiter=' ' -f 1 )" == '620981d0329aaae115dadb5203356e5b' ]
        then
            echo 'as12.exe installed in'" $DRAGON_AS12_PATH"
        else
            echo ''
        fi
    else
        echo -e "Error \x27http://dankohn.info/projects/68HC11/AsmIDE/asmide340.zip\x27 not found" >&2
    fi
fi

if [ ! -d $DRAGON_SIMULATOR_PATH/ ]
then
    mkdir $DRAGON_SIMULATOR_PATH/
else
    echo ''
fi

while [ ! -f $DRAGON_SIMULATOR_PATH/$DRAGON_SIMULATOR ]
do
    echo ''
    read -p "Place the Micro.jar simulator file in $DRAGON_SIMULATOR_PATH  and press [ENTER]: "
done

echo 'Config finished.'

exit 0
